// Every event here comes from data that actually exists in the app —
// vitals readings, the model's own annotation, and real audit-log entries
// generated by user actions (acknowledge/dismiss/vitals-entry/escalate).
// Nothing is pre-scripted fiction like "doctor notified" or "antibiotics
// administered" unless a real action in this session produced it.

import { Activity, AlertTriangle, Check, X, Plus, ArrowUpRight } from 'lucide-react';

const TYPE_META = {
  vitals: { icon: Activity, color: '#8FA0A2', label: 'Vitals recorded' },
  annotation: { icon: AlertTriangle, color: '#E0607E', label: 'AI trend detected' },
  acknowledge: { icon: Check, color: '#0E7490', label: 'Alert acknowledged' },
  dismiss: { icon: X, color: '#6B7A7C', label: 'Alert dismissed' },
  vitals_entry: { icon: Plus, color: '#20C5A0', label: 'Manual vitals entered' },
  escalate: { icon: ArrowUpRight, color: '#FDB022', label: 'Escalated to physician' },
};

function hoursLabelToDate(label) {
  // patient.vitals times look like "12h", "9h" ... "now" — convert to an
  // actual Date for sorting/display purposes only.
  const now = new Date();
  if (label === 'now') return now;
  if (label instanceof Date) return label;
  if (typeof label === 'string' && !/^\d+(?:\.\d+)?h$/.test(label) && label !== 'now') {
    const parsed = new Date(label);
    if (!Number.isNaN(parsed.getTime())) return parsed;
  }
  const hours = parseFloat(label);
  return new Date(now.getTime() - hours * 3600 * 1000);
}

export function buildTimeline(patient, auditLog) {
  const events = [];

  patient.vitals.forEach((v) => {
    events.push({
      id: `vitals-${v.recordedAt || v.time}`,
      type: 'vitals',
      time: hoursLabelToDate(v.recordedAt || v.time),
      detail: `HR ${v.hr} bpm, RR ${v.rr} /min`,
    });
  });

  if (patient.annotation) {
    events.push({
      id: 'annotation',
      type: 'annotation',
      time: hoursLabelToDate(patient.annotation.time),
      detail: patient.annotation.label,
    });
  }

  auditLog
    .filter((a) => a.patientId === patient.id)
    .forEach((a) => {
      events.push({
        id: a.id,
        type: a.type === 'dismiss' ? 'dismiss' : a.type,
        time: new Date(a.time),
        detail: a.type === 'dismiss' ? a.reason : a.type === 'vitals_entry' ? 'New reading logged manually' : 'Reviewed by ward nurse',
      });
    });

  return events.sort((a, b) => a.time - b.time).map((e) => ({ ...e, meta: TYPE_META[e.type] }));
}

export const TIMELINE_TYPE_META = TYPE_META;
